/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package searchoverenc;

import AWS.AWSConnection;
import AWS.AWSSensorDataExtractor;
import AWS.CreateTableinCloudFrame;
import static java.awt.Component.TOP_ALIGNMENT;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.TableColumnModel;
import rcc_enc.ReverseDecryptionHelper;
import rcc_enc.ReverseEncryptionHelper;
import util.Datakeeper;
import static util.Datakeeper.key;
import util.InsertDatatoTable;

/**
 *
 * @author welcome
 */
public class ViewHistoryFrame extends javax.swing.JFrame {

    /**
     * Creates new form ViewHistoryFrame
     */
    public ViewHistoryFrame() {
        super("View History Frame");
        initComponents();
        
        
       
       ((DefaultTableCellRenderer)jTable1.getTableHeader().getDefaultRenderer())
           .setHorizontalAlignment((int) TOP_ALIGNMENT);
       
       TableColumnModel columnModel = jTable1.getColumnModel();
       
       
       columnModel.getColumn(0).setPreferredWidth(150);
       columnModel.getColumn(1).setPreferredWidth(150);
       columnModel.getColumn(2).setPreferredWidth(100);
       columnModel.getColumn(3).setPreferredWidth(150);
       
       Statement st=new AWSConnection().createawsConnection();
     AWSSensorDataExtractor sd=new AWSSensorDataExtractor();
     ArrayList data=sd.getUserData(st);
     Datakeeper.data=data;
     
        int columncount= jTable1.getColumnCount();
        int rowheight=40;
    InsertDatatoTable in=new InsertDatatoTable();
    in.getDataInserted(jTable1, columncount, data,rowheight);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sensor Value 1", "Sensor Value 2", "Date", "Time"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 190, 560, 410);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Select the Date ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(710, 90, 130, 22);
        getContentPane().add(jDateChooser1);
        jDateChooser1.setBounds(850, 90, 200, 30);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sensor Value 1", "Sensor Value 2", "Date", "Time"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(640, 190, 560, 410);

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1070, 90, 90, 25);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Search Over Encrypted Data ");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(690, 140, 480, 40);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel3.setText("Cloud Data ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 140, 190, 40);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/searchoverenc/cloud-computing-502462262-5ac1130e119fa800371ba0a8.jpg"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 2830, 930);

        jMenu3.setText("Edit");
        jMenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu3ActionPerformed(evt);
            }
        });

        jMenuItem2.setText("Edit Profile");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar2.add(jMenu3);

        jMenu2.setText("Data Storage");

        jMenuItem1.setText("Streaming");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem3.setText("View History");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuBar2.add(jMenu2);

        jMenu4.setText("Settings");

        jMenuItem4.setText("Create Table on Cloud ");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem4);

        jMenuBar2.add(jMenu4);

        jMenu1.setText("Logout");

        jMenuItem5.setText("Exit");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem5);

        jMenuBar2.add(jMenu1);

        setJMenuBar(jMenuBar2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    
        Date date = jDateChooser1.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        String pdate = sdf.format(date);
        
         String encdate=new ReverseEncryptionHelper().startEncryption(pdate, Datakeeper.key);
         encdate=encdate.trim();
         ArrayList clouddata=Datakeeper.data;
         ArrayList newdata=new ArrayList();
         for (int i = 0; i < clouddata.size(); i++)
         {
             ArrayList row=(ArrayList) clouddata.get(i);
             String cdate=(String) row.get(2);
             cdate=cdate.trim();
//             int cdateint=getASCII(cdate);
//             int encint=getASCII(encdate);
           //  System.out.println("cdateint "+cdateint+" encint "+encint);
             
             
             if(cdate.equals(encdate))
             {
                
                 ArrayList temp=new ArrayList();
                 String senval1=(String) row.get(0);
                  String dsenval1=new ReverseDecryptionHelper().startDecryption(senval1, key);
                 String senval2=(String) row.get(1);
                 String dsenval2=new ReverseDecryptionHelper().startDecryption(senval2, key);

                 String date1=(String) row.get(2);
                 String ddate1=new ReverseDecryptionHelper().startDecryption(date1, key);

                 String time=(String) row.get(3);
                 String dtime=new ReverseDecryptionHelper().startDecryption(time, key);

                 
                 temp.add(dsenval1);
                 temp.add(dsenval2);
                 temp.add(ddate1);
                 temp.add(dtime);
                newdata.add(temp);
              
             }
         
         }
         System.out.println("Cloud data size "+clouddata.size());
         System.out.println("New data size "+newdata.size());
        int columncount= jTable2.getColumnCount();
        int rowheight=40;
    InsertDatatoTable in=new InsertDatatoTable();
    in.getDataInserted(jTable2, columncount, newdata,rowheight);  
         
         
         
            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        EditProfileFrame mf=new EditProfileFrame();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        mf.setVisible(true);
        mf.setSize(d);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu3ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        StreamFrame mf=new StreamFrame();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        mf.setVisible(true);
        mf.setSize(d);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ViewHistoryFrame mf=new ViewHistoryFrame();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        mf.setVisible(true);
        mf.setSize(d);

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:

        this.dispose();
        CreateTableinCloudFrame mf=new CreateTableinCloudFrame();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        mf.setVisible(true);
        mf.setSize(d);

    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem5ActionPerformed
public int getASCII (String  str)
{
    int sum=0;
    
    for (int i = 0; i < str.length(); i++)
    {
    
        char ch=str.charAt(i);
        int x=(int)ch;
        sum=sum+x;
        
        
    }
    return sum;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewHistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewHistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewHistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewHistoryFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewHistoryFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
